source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'

platform :ios, '7.0'

target :'WJCommon-master' do

pod 'WJJSON'
#pod 'WJLoggingCocoaLumberjack'
pod 'KVOController'
pod 'Masonry', '1.0.0'
pod 'Reachability', '3.2'
pod 'WJLoggingAPI', '>=2.0'

end
